In [95]:
import numpy as np
zs=24
N=10
qs=3
nr=2
A=np.zeros(int(zs/2))
B=np.zeros(int(zs/2))
winding_array=np.zeros((nr,zs,qs))
for i in range(int(zs/2)):
    if (i-1)%5 ==0 and i!= int(zs/2)-1:
        A[i]=-1*N
    if (i-3)%5 ==0:
        A[i]= 1*N
        B[i]= -1*N
    if (i-5)%5 ==0 and i!=0:
        B[i] = 1*N

In [96]:
C=-A
D=-B
A=A[::-1]
D=D[::-1]

In [97]:
for q in range(qs):
        if q==0:
            winding_array[0,9:21,q]=B
            winding_array[1,9:21,q]=C
            winding_array[0,21:24,q]=A[0:3]
            winding_array[1,21:24,q]=D[0:3]
            winding_array[0,0:9,q]=A[3:12]
            winding_array[1,0:9,q]=D[3:12]
            continue
        for i in range(2/):
            winding_array[i,:,q]=np.roll(winding_array[i,:,0],8*q) 

In [98]:
print(winding_array)

[[[ 10.   0.   0.]
  [  0. -10.   0.]
  [-10.   0.   0.]
  [  0.  10.   0.]
  [  0.   0. -10.]
  [ 10.   0.   0.]
  [  0.   0.  10.]
  [-10.   0.   0.]
  [  0.  10.   0.]
  [  0.   0. -10.]
  [  0. -10.   0.]
  [  0.   0.  10.]
  [-10.   0.   0.]
  [  0.  10.   0.]
  [ 10.   0.   0.]
  [  0. -10.   0.]
  [  0.   0.  10.]
  [-10.   0.   0.]
  [  0.   0. -10.]
  [ 10.   0.   0.]
  [  0. -10.   0.]
  [  0.   0.  10.]
  [  0.  10.   0.]
  [  0.   0. -10.]]

 [[ 10.  -0.  -0.]
  [ -0. -10.  -0.]
  [ -0.  -0.  10.]
  [-10.  -0.  -0.]
  [ -0.  -0. -10.]
  [ 10.  -0.  -0.]
  [ -0. -10.  -0.]
  [ -0.  -0.  10.]
  [ -0.  10.  -0.]
  [ -0.  -0. -10.]
  [ 10.  -0.  -0.]
  [ -0. -10.  -0.]
  [-10.  -0.  -0.]
  [ -0.  10.  -0.]
  [ -0.  -0. -10.]
  [ 10.  -0.  -0.]
  [ -0.  -0.  10.]
  [-10.  -0.  -0.]
  [ -0.  10.  -0.]
  [ -0.  -0. -10.]
  [ -0. -10.  -0.]
  [ -0.  -0.  10.]
  [-10.  -0.  -0.]
  [ -0.  10.  -0.]]]
